#!/bin/sh -e

# Run this script with cwd in the project root folder
# generated by make-job-sh.py

export IRACE_TUNING_PATH="${IRACE_TUNING_PATH:-../irace-tuning3}"
export IRACE_TUNING_RUN_DIR="${IRACE_TUNING_RUN_DIR:-runs/just-cplex}"

mkdir -p "${IRACE_TUNING_RUN_DIR}/train"
IRACE_TUNING_RUN_DIR="${IRACE_TUNING_RUN_DIR}/train" irace \
    --train-instances-dir "Instances" \
    --train-instances-file "jobs/just-cplex/instances.txt" \
    --test-instances-dir "Instances-test" \
    --test-instances-file "jobs/just-cplex/instances-test.txt" \
    --target-runner "${IRACE_TUNING_PATH}/target-runner.py" \
    --log-file "${IRACE_TUNING_RUN_DIR}/train/irace.Rdata" \
    --parameter-file "jobs/parameters.txt" \
    --max-experiment 3000 --seed 123 \
    --parallel ${IRACE_TUNING_NCPU:-1} \
    | tee "${IRACE_TUNING_RUN_DIR}/train/irace-log.log"

mkdir -p "${IRACE_TUNING_RUN_DIR}/test/train"
"${IRACE_TUNING_PATH}`/tools/generate_validation_commands.py" \
    --test-instances-dir "$Instances" \
    --test-instances-file "$jobs/just-cplex/instances.txt" \
    --target-runner "$${IRACE_TUNING_PATH}/target-runner.py" \
    --n-seed 30 \
    --log-file "$${IRACE_TUNING_RUN_DIR}/train/irace-log.log" \
    | tee "{IRACE_TUNING_RUN_DIR}/test/train/test-commands.txt" \
    | IRACE_TUNING_RUN_DIR="{IRACE_TUNING_RUN_DIR}/train/test" "{IRACE_TUNING_PATH}/tools/run_cmds.py" \
    --parallel "${IRACE_TUNING_NCPU:-1}" \
    > "{IRACE_TUNING_RUN_DIR}/test/train/test-log.log"

mkdir -p "${IRACE_TUNING_RUN_DIR}/test/test"
"${IRACE_TUNING_PATH}`/tools/generate_validation_commands.py" \
    --test-instances-dir "$Instances-test" \
    --test-instances-file "$jobs/just-cplex/instances-test.txt" \
    --target-runner "$${IRACE_TUNING_PATH}/target-runner.py" \
    --n-seed 30 \
    --log-file "$${IRACE_TUNING_RUN_DIR}/train/irace-log.log" \
    | tee "{IRACE_TUNING_RUN_DIR}/test/test/test-commands.txt" \
    | IRACE_TUNING_RUN_DIR="{IRACE_TUNING_RUN_DIR}/train/test" "{IRACE_TUNING_PATH}/tools/run_cmds.py" \
    --parallel "${IRACE_TUNING_NCPU:-1}" \
    > "{IRACE_TUNING_RUN_DIR}/test/test/test-log.log"


