#!/bin/sh -e

# Run this script with cwd in the project root folder
# generated by make-job-sh.py

export IRACE_TUNING_PATH="${IRACE_TUNING_PATH:-../irace-tuning3}"
export IRACE_TUNING_RUN_DIR="${IRACE_TUNING_RUN_DIR:-runs/cplex_rcw}"

mkdir -p "${IRACE_TUNING_RUN_DIR}/train"
IRACE_TUNING_RUN_DIR="${IRACE_TUNING_RUN_DIR}/train" irace \
    --train-instances-dir "Instances" \
    --train-instances-file "jobs/cplex_rcw/instances.txt" \
    --test-instances-dir "Instances-test" \
    --test-instances-file "jobs/cplex_rcw/instances-test.txt" \
    --target-runner "${IRACE_TUNING_PATH}/target-runner.py" \
    --log-file "${IRACE_TUNING_RUN_DIR}/train/irace.Rdata" \
    --parameter-file "jobs/parameters.txt" \
    --max-experiment 3000 --seed 123 \
    --parallel ${IRACE_TUNING_NCPU:-1} \
    | tee "${IRACE_TUNING_RUN_DIR}/train/irace-log.log"

