[surrogate_args]
pyrfr_wrapper = "target_algorithms/surrogate/lingeling_circuitfuzz/pyrfr_wrapper.lingeling_circuitfuzz.par10.random.pkl"
pyrfr_model = "target_algorithms/surrogate/lingeling_circuitfuzz/pyrfr_model.lingeling_circuitfuzz.par10.random.bin"
config_space = "target_algorithms/surrogate/lingeling_circuitfuzz/config_space.lingeling_circuitfuzz.par10.random.pcs"
inst_feat_dict = "target_algorithms/surrogate/lingeling_circuitfuzz/inst_feat_dict.lingeling_circuitfuzz.par10.random.json"

[irace_args]
parameter_file = "target_instances/surrogate/lingeling_circuitfuzz/config_space.lingeling_circuitfuzz.par10.random.irace.txt"
train_instances_file = "target_instances/surrogate/lingeling_circuitfuzz/train-1.txt"
test_instances_file = "target_instances/surrogate/lingeling_circuitfuzz/validation-1.txt"
digits = 10
max_time = "172800"
bound_max = "300"
